### ISSUE TITLE
Grafana Datasource / {base_url}/test.json API 호출 에러

### ISSUE THREAD

**Issue by junhyuck-yoo** [gnh1201/reasonableframework#138]
Grafana 에 Datasource로 사용하기 위해 json 파일 작성 후 설명과 같이 base_url/test.json 을 호출하였지만

reasonableframework 메인 화면으로 넘어갑니다.

일반적인 로직 수행을 위한 base_url/?route=.. 의 경우는 정상 동작합니다.

**Comment by junhyuck-yoo** [comment]
http://:base_url/test.php  정상이라면 /home/userdir/public_html/route/test.php에 접근해야합니다.

문제 상황은 http://:base_url/test.php 으로 접근하면 /home/userdir/public_html/test.php 으로 접근하려 합니다.

http://:base_url/?route=test 으로 요청을 했을 때만 /home/userdir/public_html/route/test.php 으로 접근합니다.

/home/userdir/public_html/.htaccess 내용은 아래와 같습니다.

RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /~gw/index.php/$1 [L]

**Comment by gnh1201** [comment]
`/home/userdir/public_html/route/test.php` 이므로 경로에 `~/gw`가 포함되어 있지 않습니다.

/home/userdir/public_html/.htaccess 내용을 아래와 같이 수정하여 주세요.

```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L]
```

이후 정상적인 동작이 가능합니다.

**Comment by junhyuck-yoo** [comment]
해당 내용으로 수정하여도 /~gw/?route=test 의 경로도 사용 가능한가요 ?

**Comment by gnh1201** [comment]
Fix #138 Routing failure #140 에서 반영하였습니다. 변경사항을 확인해주세요.
