### ISSUE TITLE
[unspecified] Gmail 또는 Naver 이메일 발송이 안됨.

### ISSUE THREAD

**Issue by gnh1201** [gnh1201/reasonableframework#33]
메일 서비스 제공자는 스팸 방지를 위한 프로그램을 모든 사용자에게 광범위하게 제공합니다.
수신 받을 메일이 스팸이 아닌지 판단하는 기준으로서 가장 많이 사용되는 것은 RBL과 PTR 입니다.

일반적인 사용자는 PTR를 설정하는 것만으로도 신뢰 가능한 발송처로 인식될 수 있습니다.

PTR 레코드 등록은 공공 DNS를 소유한 사업자만이 가능합니다.
국내 서버의 경우 KT(코넷), LG U+(보라넷), SK브로드밴드(ISP DNS 담당 부서 연락처가 별도로 없으므로, 고객센터를 통해 여러번 연결 시도를 해야합니다.)을 통해 PTR 등록을 하실 수 있습니다.

해외 서버이거나 클라우드 서비스 이용 시, 호스팅 업체가 PTR(Reverse DNS) 설정을 제공하는지 확인하세요.
만약, 모든 경우의 수가 여의치 않은 경우 클라우드플레어(Cloudflare)를 이용하는 방법도 있습니다.

PTR 레코드를 추가하고, 해당 서버에 할당된 IP 주소를 등록하시면 통상 영업일 5일 이내에 반영됩니다.

**Comment by gnh1201** [comment]
국내 사용자 대상 서비스인 경우 SPF 등록을 함께 진행할 수 있습니다.
support@exts.kr 으로 도메인, IP주소와 사업자등록증 보내주시면 처리해드릴 수 있습니다.

**Comment by gnh1201** [comment]
매우 드문 경우입니다만, 한국 이메일 서비스를 차단하는 서버에 이메일을 발송해야 하는 경우 (RBL 중 korea.services.net의 경우 한국 IP 대역을 모두 차단함), 메일 발송을 위한 대체 서비스(Mailgun, Sendgrid 등)을 사용하여야 합니다.

**Comment by maxswjeon** [comment]
일부 국내 서비스에서는 KISA Whitedomain을 참고하는 경우가 있습니다.
