### ISSUE TITLE
Select Option 에저 지정된 값을 유지 하고자 하는 경우의 문장

### ISSUE THREAD

**Issue by bmcadrian** [gnh1201/reasonableframework#43]
select Option 질문 하나, Select Option 에서 선택한 값을 유지 하는 거 만들어 보고 있는데..
자꾸 Parse error: syntax error, unexpected '<' in /ndklok/www/po2/view/staff/view_stafflist.php on line 113오류가 난다..

문장이 잘 못 된건지 한번 봐주세요 ?

<select name="limit">
   <option value="10" <?php if(<?php echo $limit;?> == '10'){echo("selected");}?>>10</option>
   <option value="25">25</option>
   <option value="50">50</option>
   <option value="100">100</option>
</select>

**Comment by gnh1201** [comment]
select 태그와 option 태그가 모두 포함된 코드를 남겨주시면 확인해보겠습니다.

**Comment by gnh1201** [comment]
종결합니다. 이슈사항이 있는 경우 언제든 남겨주세요.
