### ISSUE TITLE
$bind 값 생략시 오류

### ISSUE THREAD

**Issue by bmcadrian** [gnh1201/reasonableframework#44]
table에 있는 전체 자료를 가져올 경우, 아래와 같이 $bind 값을 생략하고 자료를 가져오게되면 오류가 발생합니다.

$distributors = exec_db_fetch_all($sql);

오류 사항 :
Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /ndklok/www/po2/system/database.php on line 224 array(0) { }

내용 확인 부탁합니다.

**Comment by gnh1201** [comment]
Warning: Invalid argument supplied for foreach() in /path/to/system/database.php on line 313 Warning: array_keys() expects parameter 1 to be array, boolean given in /path/to/system/database.php on line 92 Warning: usort() expects parameter 1 to be array, null given in /path/to/system/database.php on line 94 Warning: Invalid argument supplied for foreach() in /path/to/system/database.php on line 95 array(0) { } Warning: Invalid argument supplied for foreach() in /path/to/system/database.php on line 313 Warning: array_keys() expects parameter 1 to be array, boolean given in /path/to/system/database.php on line 92 Warning: usort() expects parameter 1 to be array, null given in /path/to/system/database.php on line 94 Warning: Invalid argument supplied for foreach() in /path/to/system/database.php on line 95

**Comment by gnh1201** [comment]
1. SQL문 작성 단계와, SQL QUERY 단계의 BIND 항목은 일치하여야 합니다.
2. 추가로 보내주신 오류는 671aa580badc546fce886a29d57c89ff7748c391 에 반영되어, 다음 배포(릴리즈)때 적용될 예정입니다. (해결 방법을 개별 안내해드리겠습니다.)

감사합니다.
