### ISSUE TITLE
Delete Route가 Call 이 안됨

### ISSUE THREAD

**Issue by bmcadrian** [gnh1201/reasonableframework#46]
남현씨, view_cartlist 뷰에서 Javascript은 불러지는데, cartdelete라는 Route쪽으로 넘어가지가 않는데 이유를 모르겠다. 이것도 좀 봐주면 감사

<div class="row">

	
	<section class="content-header box-shadow box-design">
		<div class="col-mid-12 in-block">
			<div class="col-mid-6 in-block">
				<h2><?php echo $title; ?></h2>
				
			</div>
			
		</div>
	</section>

	
	<div id="listview" class="view_orderlist"> 
		<form id="listform" method="post" action="<?php echo base_url(); ?>">
			
			
			<div class="hidden">
				<input type="hidden" name="route" value="addcart/cartlist">
			</div>
		
			<section class="content box-shadow box-design">
				<div class="row mg-bt-15">
					
					<div class="lctrl fl-left">
						<button id="btn_add_item" class="search-btn mg-lf-5">
							<i class="fa fa-plus"></i> Add Item
						</button>
						<button id="btn_delete" class="cancel-bgn mg-lf-5 red">
							<i class="fa fa-minus"></i> Delete Selected Item
						</button>
					</div>
					
					<div class="rctrl fl-right p-right">
						<button class="confirmed-bgn mg-lf-5 bg-gray">
							<i class="fa fa-save"></i> Save All
						</button>
					</div>
					<div class="rctrl fl-right p-right">
						<button class="verifying-bgn mg-lf-5">
							<i class="fa fa-upload"></i> Excel Upload
						</button>
					</div>
					<div class="rctrl fl-right p-right">
						<button id="btn_issuepo_with_selected" class="confirmed-bgn mg-lf-5">
							<i class="fa fa-share"></i> ISSUE PO Selected
						</button>
					</div>
					<div class="rctrl fl-right p-right">
						<button id="btn_issuepo_all" class="confirmed-bgn mg-lf-5">
							<i class="fa fa-share"></i> ISSUE PO All
						</button>
					</div>
				</div>

				
				<table class="table-form height-40 vertical-middle">
					<colgroup>
						<col style="width: 2%;"></col>
						<col style="width: 5%;"></col>
						<col style="width: 10%"></col>
						<col style="width: 18%;"></col>
						<col style="width: 12%;"></col>
						<col style="width: 5%;"></col>
						<col style="width: 10%;"></col>
						<col></col>
						<col></col>
						<col style="width: 7%;"></col>
					</colgroup>
					
					<thead>
						<tr>
							<th><input type="checkbox" id="chk_id_all"/></th>
							<th>Division</th>
							<th>Part #</th>
							<th>Description</th>
							<th>Specification</th>
							<th>Order Qty</th>
							<th>Delivery Request Date</th>
							<th>Remark</th>
							<th>Comment</th>
							<th>Save/Del</th>
						</tr>
					</thead>
					
					<tbody>
	<?php
					foreach($carttemps as $carttemp) {
						$rowid = make_random_id(16);					

						$item_data = serialize(array(
							"id" => $carttemp['id'],
							"item_cd" => $carttemp['item_cd'],
							"item_nm" => $carttemp['item_nm'],
							"item_spec" => $carttemp['item_spec'],
							"item_mode" => $carttemp['item_mode'],
						));
	?>
						<tr>
							<td><input type="checkbox" class= "chk_all" name="chk_rowid[]" value="<?php echo $rowid; ?>"></td>
							<td><?php echo $carttemp['item_mode']; ?></td>							
							<td class="td-hover">
								
								<?php echo $carttemp['item_cd']; ?>
								<a class="link_detail" href="<?php echo get_route_link("addcart/itemdetail", array("id" => $carttemp['id'])); ?>"data-id="<?php echo $carttemp['id']; ?>"<?php echo $carttemp['item_cd']; ?></a>
								<div class="td-sub-title">
									<a class="link_detail" href="<?php echo get_route_link("addcart/itemdetail", array("id" => $carttemp['id'])); ?>" data-id="<?php echo $carttemp['id']; ?>">VIEW</a>
									<span>|</span>
									<a class="link_delete" href="<?php echo get_route_link("addcart/cartdelete", array("id" => $carttemp['id'])); ?>" data-id="<?php echo $carttemp['id']; ?>">DELETE</a>
								</div>

								<textarea name="chk_item_data[<?php echo $rowid; ?>]" style="display: none;"><?php echo $item_data; ?></textarea>
							</td>
							<td><?php echo $carttemp['item_nm']; ?></td>
							<td><?php echo $carttemp['item_spec']; ?></td>
							<td>
								<div class="input-group">
									<input type="text" name="chk_item_qty[<?php echo $rowid; ?>]" placeholder="0" value="<?php echo $carttemp['qty']; ?>" class="p-center height-18 width-8em"/>
									<div class="input-group-up-down" id="search_st_dt_icon">
										<i class="fa fa-chevron-up input-up-btn"></i>
										<i class="fa fa-chevron-down input-down-btn"></i>
									</div>
								</div>
							</td>
							<td>
								<input type="date" name="chk_item_drdate[<?php echo $rowid; ?>]" class="p-center"/ value="<?php echo $delivery_request_date; ?>">
							</td>
							<td>
								<input type="text" name="chk_item_remark[<?php echo $rowid; ?>]" class="p-center"/ value="">
							</td>
							<td><input type="text" name="chk_item_comment[<?php echo $rowid; ?>]" class="p-center"/ value=""></td>
							<td>
								<button class="confirmed-bgn mg-lf-5 bg-gray">
									<i class="fa fa-save"></i>
								</button>
								<button class="confirmed-bgn mg-lf-5 bg-red">
									<i class="fa fa-trash"></i>
								</button>
							</td>
						</tr>
	<?php
					}
	?>
					</tbody>
				</table>
			</section>
		</form>
	</div>

	<div id="viewer" class="col-mid-8 fl-right"></div>
</div>

<script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
<script type="text/javascript">//<!--<![CDATA[
	var base_url = "<?php echo base_url(); ?>";
	var toggle = false;
	var slide = false;
	var row_id = parseInt("<?php echo $id; ?>");
	document.title = "CART List - DKLOK PO System";

	jQuery(document).ready(function($){

		var toggle_viewer = function() {
			// Toggle 이 열려있으면
			if(toggle == true) {
				$("#viewer").css("display", "none");
				$("#listview").removeClass("col-mid-4");
				$("#listview").removeClass("fl-left");
				$("#listview").find(".toggle").css("display", "");
				$("#toggle-icon").removeClass("fa-angle-double-right");
				$("#toggle-icon").addClass("fa-angle-double-left");
			} else {
				$("#viewer").css("display", "");
				$("#listview").addClass("col-mid-4");
				$("#listview").addClass("fl-left");
				// 테이블에 컬럼을 숨기기 위한 것
				$("#listview").find(".toggle").css("display", "none");
				$("#toggle-icon").addClass("fa-angle-double-left");
				$("#toggle-icon").removeClass("fa-angle-double-left");
				$("#toggle-icon").addClass("fa-angle-double-right");
			}

			toggle = !toggle;
		};

		var get_viewer_contents = function(id) {
			$.get(base_url, {
				"route": "addcart/cartdetail",
				"id": id,
				"method": "ajax",
			}, function(data) {
				// padding-left에 20px를 주기위한 처리
				var contents = $("<div/>").addClass("viewer_in").html(data);
				$("#viewer").html(contents);
			});
		};

		var trigger_delete = function(id) {
			$.get(base_url, {
				"route": "addcart/cartdelete",
				"id": id,
				"method": "ajax"
			}, function(data) {
				// padding-left에 20px를 주기위한 처리
				var contents = $("<div/>").addClass("viewer_in").html(data);
				$("#viewer").html(contents);
			});
		};

		$(".td-hover").hover(function(){
			if(slide == false) {
				// 현재 Row 의 Object를 찾아서 해당 Row만 반영되게 처리
				$(this).find(".td-sub-title").css("display", "block");
				$(this).find(".td-sub-title").css("text-align", "center");
				slide = true;
			}else{
				$(this).find(".td-sub-title").css("display", "none");
				slide = false;
			}
		});

		$("a.link_detail").click(function(e) {
			var $id = $(this).data("id");
			get_viewer_contents($id);
			if(toggle == false) {
				toggle_viewer();
			}
			e.preventDefault();
			return false;
		});

		$("a.link_delete").click(function(e) {
			var $id = $(this).data("id");

			if(confirm("Are you sure? - link")) {
				trigger_delete($id);
				window.location.reload();
			}

			e.preventDefault();
			return false;
		});

		$("a.toggle_viewer").click(function() {
			// alert("toggle was clicked");
			toggle_viewer();
		});

		$("#viewer").css("display", "none");

		$("#form_distributorsearch").each(function() {
			var $form = $(this);

			$form.find("select[name='manager']").change(function() {
				$form.submit();
			});
		});

		// ID 값이 존재하면
		if(row_id > 0) {
			get_viewer_contents(row_id);
			if(toggle == false) {
				toggle_viewer();
			}
		} else {
			// 리스트에 글이 있는지 검사
			$("#listview").find("[data-id]:first").each(function() {
				// 상단 Toggle을 클릭하게 될 경우, 첫 번째 주문의 상세내용을 보이도록 함.
				get_viewer_contents($(this).data("id"));
			});
		}

		// 전체삭제 버튼 클릭
		$("#btn_delete").click(function() {
			if(confirm("Are you sure?")) {
				$("#listform").submit();
			}
		});

		// Check Box 전체 클릭시 전체 선택
		$( '#chk_id_all' ).click( function() {
			$( '.chk_all' ).prop( 'checked', this.checked );
		} );

		// 추가 버튼
		$("#btn_add").click(function() {
			get_viewer_contents("");
			toggle_viewer();
		});

		// 선택된 품목만 주문 처리
		$("#btn_issuepo_with_selected").click(function() {
			var $form = $("#listform");
			$form.find("input[name='route']").val("addcart/cartdetail");
			$form.submit();
		});

		// 선택된 품목만 주문 처리
		$("#btn_issuepo_all").click(function() {
			var $form = $("#listform");
			$form.find("input[name='route']").val("addcart/cartdetail");
			$form.submit();
		});

		// 품목 추가시
		$("#btn_add_item").click(function() {
			var $form = $("#listform");
			$form.find("input[name='route']").val("addcart/addcartlist");
			$form.submit();
		});
	});
</script>

**Comment by gnh1201** [comment]
이슈를 닫겠습니다. 감사합니다.
